# Generated by Django 4.1.3 on 2022-12-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.CharField(max_length=200)),
                ("shortened", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "urls",
            },
        ),
    ]
