# Generated by Django 4.1.3 on 2022-12-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
